name: "Build & Test"
on: # rebuild any PRs and main branch changes
  repository_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Deployment Started
        notification-style: accent
        timezone: America/Denver
        verbose-logging: true
    - run: sleep 1
    - uses: ./
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Warning! Something Not Quite Right
        notification-style: warning
        timezone: America/Denver
        verbose-logging: true
    - run: sleep 1
    - uses: ./
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: OMG!! Something Exploded
        notification-style: attention
        timezone: America/Denver
        verbose-logging: true
    - run: sleep 1
    - uses: ./
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Whew! Everything is right with the world again!
        notification-style: good
        timezone: America/Denver
        verbose-logging: true
    - run: sleep 1
    - uses: ./
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: "Emojify! 🕹️ &#x2705;"
        notification-style: good
        timezone: America/Denver
        verbose-logging: true
